# SPDX-License-Identifier: MIT

# GitHub Dependabot configuration file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
    - "/"
    - "/.github/actions"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
    - "/.github/workflows"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directories:
    - "/"
    schedule:
      interval: "daily"
